# Generated by Django 5.2 on 2025-05-03 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('is_vaccinated', models.BooleanField(default=False)),
                ('weight', models.FloatField()),
                ('color', models.CharField(choices=[('BLK', 'Black'), ('WHT', 'White'), ('GRY', 'Gray'), ('BRN', 'Brown'), ('ORG', 'Orange')], default='BLK', max_length=3)),
                ('breed', models.CharField(choices=[('PER', 'Persian'), ('SIA', 'Siamese'), ('BSH', 'British Shorthair'), ('BEN', 'Bengal'), ('RAG', 'Ragdoll'), ('SPH', 'Sphynx'), ('MCO', 'Maine Coon'), ('ABY', 'Abyssinian')], default='PER', max_length=3)),
            ],
        ),
    ]
