# Generated by Django 4.2.21 on 2025-06-24 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='is_vaccinated',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
