# Generated by Django 4.2.21 on 2025-06-26 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_alter_cat_is_vaccinated'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='adoption_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
